from __future__ import annotations

import json
import math
import os
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .parser import parse_slx
from .patching import PatchDocument, load_patch, validate_patch_for_model
from .slx_path import relative_to_system


@dataclass(frozen=True)
class MatlabStatus:
    available: bool
    executable: str | None
    detail: str


def validate_simulation_stop_time(value: Any) -> str:
    """Return a bounded numeric Simulink StopTime string.

    Workbench simulation is intentionally a convenience execution path, not an
    arbitrary-expression surface.  Users who need workspace expressions can use
    the explicit MATLAB Command Window / script editor instead.
    """

    text = str(value if value is not None else "10").strip() or "10"
    if len(text) > 64 or "\n" in text or "\r" in text:
        raise ValueError("invalid simulation stop time")
    try:
        numeric = float(text)
    except ValueError as exc:
        raise ValueError("simulation stop time must be a non-negative finite number") from exc
    if not math.isfinite(numeric) or numeric < 0 or numeric > 1e12:
        raise ValueError("simulation stop time must be a non-negative finite number")
    return format(numeric, ".12g")


def _known_matlab_candidates() -> list[Path]:
    """Return conventional MATLAB executable locations, newest release first.

    MATLAB is not always added to PATH on desktop installations, especially on
    Windows.  Keep this discovery deliberately filesystem-only: no registry
    writes, no subprocess launches, and no dependency on MATLAB itself.
    """

    candidates: list[Path] = []
    if os.name == "nt":
        roots: list[Path] = []
        for value in (os.environ.get("ProgramW6432"), os.environ.get("ProgramFiles"), r"C:\Program Files"):
            if value:
                root = Path(value) / "MATLAB"
                if root not in roots:
                    roots.append(root)
        for root in roots:
            candidates.extend(root.glob("R*/bin/matlab.exe"))
    elif sys.platform == "darwin":
        candidates.extend(Path("/Applications").glob("MATLAB_R*.app/bin/matlab"))
    else:
        for root in (Path("/usr/local/MATLAB"), Path("/opt/MATLAB")):
            candidates.extend(root.glob("R*/bin/matlab"))
    return sorted((item for item in candidates if item.is_file()), key=lambda item: str(item), reverse=True)


def find_matlab(explicit: str | Path | None = None) -> MatlabStatus:
    configured = str(explicit) if explicit else os.environ.get("SLX_DIFF_MATLAB")
    if configured:
        path = (
            shutil.which(configured)
            if os.path.sep not in configured and "/" not in configured
            else configured
        )
        if path and Path(path).exists():
            return MatlabStatus(True, str(Path(path).resolve()), "MATLAB executable found")
        if path and shutil.which(path):
            resolved = shutil.which(path)
            return MatlabStatus(True, resolved, "MATLAB executable found")
        return MatlabStatus(False, configured, f"MATLAB executable not found: {configured}")

    on_path = shutil.which("matlab")
    if on_path:
        return MatlabStatus(True, str(Path(on_path).resolve()), "MATLAB executable found on PATH")

    known = _known_matlab_candidates()
    if known:
        return MatlabStatus(
            True, str(known[0].resolve()), "MATLAB executable found in a standard install location"
        )
    return MatlabStatus(False, None, "MATLAB executable not found on PATH or in a standard install location")


def _matlab_quote(text: str) -> str:
    return text.replace("'", "''")


def _matlab_command(executable: str | Path) -> list[str]:
    """Build a subprocess command for MATLAB or a script-based test double.

    On POSIX, a test double with a Python shebang can be executed directly.
    Windows does not honor a shebang for extensionless files, so explicitly
    invoke Python for script-based doubles while leaving a real ``matlab.exe``
    untouched.  This keeps the public ``matlab=`` override portable without
    changing the command line used by real MATLAB installations.
    """

    path = Path(executable)
    if os.name == "nt" and path.is_file():
        try:
            first_line = path.open("rb").readline(256).lower()
        except OSError:
            first_line = b""
        if path.suffix.lower() == ".py" or (first_line.startswith(b"#!") and b"python" in first_line):
            return [sys.executable, str(path)]
    return [str(executable)]


def _runner_source(request_path: Path, result_path: Path) -> str:
    request = _matlab_quote(str(request_path.resolve()))
    result = _matlab_quote(str(result_path.resolve()))
    return f"""% Generated by slx-diff. Do not edit.
requestPath = '{request}';
resultPath = '{result}';
result = struct('ok', false, 'message', '', 'output_model', '', 'simulation', struct());
loadedName = '';
try
    req = jsondecode(fileread(requestPath));
    inputPath = char(req.input_model);
    outputPath = char(req.output_model);
    h = load_system(inputPath);
    loadedName = get_param(h, 'Name');

    ops = req.patch.operations;
    if ~isempty(ops)
        if iscell(ops), ops = [ops{{:}}]; end
        for k = 1:numel(ops)
            op = ops(k);
            if ~strcmp(char(op.op), 'set_param')
                error('slxdiff:UnsupportedOperation', 'Unsupported patch operation: %s', char(op.op));
            end
            target = loadedName;
            rel = char(op.block_path);
            if ~isempty(rel), target = [loadedName '/' rel]; end
            parameter = char(op.parameter);
            expected = char(op.before);
            desired = char(op.after);
            current = get_param(target, parameter);
            if isnumeric(current), current = mat2str(current); end
            if isstring(current), current = char(current); end
            if ~ischar(current), current = char(string(current)); end
            if ~strcmp(current, expected)
                error('slxdiff:PatchConflict', 'Patch conflict at %s/%s: expected "%s", found "%s"', target, parameter, expected, current);
            end
            set_param(target, parameter, desired);
        end
    end

    save_system(loadedName, outputPath);
    loadedName = get_param(h, 'Name');
    result.output_model = outputPath;

    if isfield(req, 'simulate') && req.simulate.enabled
        stopTime = char(req.simulate.stop_time);
        started = tic;
        simOut = sim(loadedName, 'StopTime', stopTime, 'ReturnWorkspaceOutputs', 'on');
        elapsed = toc(started);
        vars = {{}};
        try
            vars = who(simOut);
        catch
        end
        series = slxstudio_collect_sim_series(simOut);
        result.simulation = struct('ran', true, 'stop_time', stopTime, 'elapsed_seconds', elapsed, 'output_variables', {{vars}}, 'series', series);
    else
        result.simulation = struct('ran', false);
    end

    result.ok = true;
    result.message = 'Patch applied successfully';
catch ME
    result.ok = false;
    result.message = ME.message;
    result.identifier = ME.identifier;
end
try
    if ~isempty(loadedName), close_system(loadedName, 0); end
catch
end
fid = fopen(resultPath, 'w');
fprintf(fid, '%s', jsonencode(result));
fclose(fid);
if ~result.ok
    error('slxdiff:BridgeFailed', '%s', result.message);
end

function series = slxstudio_collect_sim_series(simOut)
series = struct('name', {{}}, 'time', {{}}, 'data', {{}});
try
    names = who(simOut);
catch
    names = {{}};
end
for n = 1:numel(names)
    if numel(series) >= 12, break; end
    name = char(names{{n}});
    try
        value = get(simOut, name);
        series = slxstudio_append_series(series, name, value);
    catch
    end
end
end

function series = slxstudio_append_series(series, name, value)
if numel(series) >= 12, return; end
if isa(value, 'timeseries')
    series = slxstudio_append_timeseries(series, name, value);
    return;
end
try
    if isa(value, 'Simulink.SimulationData.Dataset')
        count = numElements(value);
        for j = 1:count
            if numel(series) >= 12, break; end
            element = value{{j}};
            elementName = name;
            try
                if ~isempty(element.Name), elementName = [name '/' char(element.Name)]; end
            catch
            end
            try
                series = slxstudio_append_timeseries(series, elementName, element.Values);
            catch
            end
        end
    end
catch
end
end

function series = slxstudio_append_timeseries(series, name, ts)
try
    if ~isa(ts, 'timeseries'), return; end
    time = double(ts.Time(:));
    data = double(ts.Data(:));
    if isempty(time) || numel(time) ~= numel(data) || ~isreal(time) || ~isreal(data), return; end
    finiteMask = isfinite(time) & isfinite(data);
    time = time(finiteMask); data = data(finiteMask);
    if isempty(time), return; end
    maxPoints = 1500;
    if numel(time) > maxPoints
        idx = unique(round(linspace(1, numel(time), maxPoints)));
        time = time(idx); data = data(idx);
    end
    series(end+1) = struct('name', char(name), 'time', time(:)', 'data', data(:)'); %#ok<AGROW>
catch
end
end
"""


def _run_matlab_request(
    request: dict[str, Any],
    *,
    matlab: str | Path | None = None,
    timeout: float = 300.0,
    on_process: Callable[[subprocess.Popen[str]], None] | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> dict[str, Any]:
    status = find_matlab(matlab)
    if not status.available or not status.executable:
        raise RuntimeError(status.detail)

    with tempfile.TemporaryDirectory(prefix="slx-diff-matlab-") as temp_dir:
        root = Path(temp_dir)
        request_path = root / "request.json"
        result_path = root / "result.json"
        runner_path = root / "run_slxdiff.m"
        request_path.write_text(json.dumps(request, ensure_ascii=False), encoding="utf-8")
        runner_path.write_text(_runner_source(request_path, result_path), encoding="utf-8")
        batch = f"run('{_matlab_quote(str(runner_path.resolve()))}')"
        proc = subprocess.Popen(
            [*_matlab_command(status.executable), "-batch", batch],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        if on_process:
            on_process(proc)
        try:
            stdout, stderr = proc.communicate(timeout=timeout)
        except subprocess.TimeoutExpired as exc:
            proc.kill()
            proc.communicate()
            raise RuntimeError(f"MATLAB bridge timed out after {timeout:g} seconds") from exc
        was_cancelled = bool(cancelled()) if cancelled else False
        if result_path.exists():
            try:
                result = json.loads(result_path.read_text(encoding="utf-8"))
            except json.JSONDecodeError as exc:
                raise RuntimeError(f"MATLAB bridge returned invalid JSON: {exc}") from exc
        elif was_cancelled:
            return {
                "ok": False,
                "cancelled": True,
                "message": "MATLAB operation cancelled",
                "stdout": stdout or "",
                "stderr": stderr or "",
            }
        else:
            detail = (stderr or stdout or "MATLAB exited without a bridge result").strip()
            raise RuntimeError(detail)
        if was_cancelled:
            result["cancelled"] = True
            result.setdefault("stdout", stdout or "")
            result.setdefault("stderr", stderr or "")
            return result
        if proc.returncode != 0 or not result.get("ok"):
            message = result.get("message") or stderr or stdout or "MATLAB bridge failed"
            raise RuntimeError(str(message).strip())
        result.setdefault("cancelled", False)
        return result


def apply_patch_with_matlab(
    model_path: str | Path,
    patch: PatchDocument | str | Path,
    *,
    output_path: str | Path,
    matlab: str | Path | None = None,
    simulate: bool = False,
    stop_time: str = "10",
    timeout: float = 300.0,
    on_process: Callable[[subprocess.Popen[str]], None] | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> dict[str, Any]:
    source = Path(model_path).resolve()
    output = Path(output_path).resolve()
    document = load_patch(patch) if isinstance(patch, (str, Path)) else patch
    model = parse_slx(source)
    validate_patch_for_model(document, model, source_path=source, require_hash=True)
    output.parent.mkdir(parents=True, exist_ok=True)
    normalized_stop_time = validate_simulation_stop_time(stop_time) if simulate else "10"
    request = {
        "input_model": str(source),
        "output_model": str(output),
        "patch": document.to_dict(),
        "simulate": {"enabled": bool(simulate), "stop_time": normalized_stop_time},
    }
    return _run_matlab_request(
        request, matlab=matlab, timeout=timeout, on_process=on_process, cancelled=cancelled
    )


def _blueprint_runner_source(request_path: Path, result_path: Path) -> str:
    request = _matlab_quote(str(request_path.resolve()))
    result = _matlab_quote(str(result_path.resolve()))
    return f"""% Generated by SLX Studio from a validated model blueprint. Do not edit.
requestPath = '{request}';
resultPath = '{result}';
result = struct('ok', false, 'message', '', 'output_model', '', 'model_name', '', 'block_count', 0, 'connection_count', 0);
loadedName = '';
try
    req = jsondecode(fileread(requestPath));
    modelName = char(req.model_name);
    outputPath = char(req.output_model);
    new_system(modelName);
    loadedName = modelName;

    blocks = req.blocks;
    if ~isempty(blocks)
        if iscell(blocks), blocks = [blocks{{:}}]; end
        for k = 1:numel(blocks)
            block = blocks(k);
            dest = [modelName '/' char(block.name)];
            add_block(char(block.library), dest);
            pos = double(block.position(:)');
            set_param(dest, 'Position', pos);
            if isfield(block, 'parameters')
                names = fieldnames(block.parameters);
                for p = 1:numel(names)
                    parameter = names{{p}};
                    value = block.parameters.(parameter);
                    if isnumeric(value), value = mat2str(value); end
                    if isstring(value), value = char(value); end
                    if ~ischar(value), value = char(string(value)); end
                    set_param(dest, parameter, value);
                end
            end
        end
    end

    connections = req.connections;
    if ~isempty(connections)
        if iscell(connections), connections = [connections{{:}}]; end
        for k = 1:numel(connections)
            conn = connections(k);
            src = [char(conn.src_name) '/' num2str(conn.src_port)];
            dst = [char(conn.dst_name) '/' num2str(conn.dst_port)];
            add_line(modelName, src, dst, 'autorouting', 'on');
        end
    end

    if isfield(req, 'model_parameters')
        names = fieldnames(req.model_parameters);
        for p = 1:numel(names)
            parameter = names{{p}};
            value = req.model_parameters.(parameter);
            if isnumeric(value), value = mat2str(value); end
            if isstring(value), value = char(value); end
            if ~ischar(value), value = char(string(value)); end
            set_param(modelName, parameter, value);
        end
    end

    save_system(modelName, outputPath);
    result.ok = true;
    result.message = 'Blueprint built successfully';
    result.output_model = outputPath;
    result.model_name = modelName;
    result.block_count = numel(blocks);
    result.connection_count = numel(connections);
catch ME
    result.ok = false;
    result.message = ME.message;
    result.identifier = ME.identifier;
end
try
    if ~isempty(loadedName), close_system(loadedName, 0); end
catch
end
fid = fopen(resultPath, 'w');
fprintf(fid, '%s', jsonencode(result));
fclose(fid);
if ~result.ok
    error('slxdiff:BlueprintBuildFailed', '%s', result.message);
end
"""


def _run_blueprint_matlab_request(
    request: dict[str, Any],
    *,
    matlab: str | Path | None = None,
    timeout: float = 300.0,
) -> dict[str, Any]:
    status = find_matlab(matlab)
    if not status.available or not status.executable:
        raise RuntimeError(status.detail)
    with tempfile.TemporaryDirectory(prefix="slx-studio-blueprint-") as temp_dir:
        root = Path(temp_dir)
        request_path = root / "request.json"
        result_path = root / "result.json"
        runner_path = root / "build_slx_blueprint.m"
        request_path.write_text(json.dumps(request, ensure_ascii=False), encoding="utf-8")
        runner_path.write_text(_blueprint_runner_source(request_path, result_path), encoding="utf-8")
        batch = f"run('{_matlab_quote(str(runner_path.resolve()))}')"
        proc = subprocess.run(
            [*_matlab_command(status.executable), "-batch", batch],
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
        if not result_path.exists():
            detail = (proc.stderr or proc.stdout or "MATLAB exited without a blueprint result").strip()
            raise RuntimeError(detail)
        try:
            result = json.loads(result_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise RuntimeError(f"MATLAB blueprint bridge returned invalid JSON: {exc}") from exc
        if proc.returncode != 0 or not result.get("ok"):
            message = result.get("message") or proc.stderr or proc.stdout or "MATLAB blueprint build failed"
            raise RuntimeError(str(message).strip())
        return result


def build_blueprint_with_matlab(
    blueprint,
    *,
    output_path: str | Path,
    matlab: str | Path | None = None,
    timeout: float = 300.0,
    overwrite: bool = False,
) -> dict[str, Any]:
    """Build a validated SLX Studio blueprint using a restricted MATLAB command set."""
    from .blueprint import BLOCK_CATALOG, ModelBlueprint, blueprint_from_dict

    document = blueprint if isinstance(blueprint, ModelBlueprint) else blueprint_from_dict(blueprint)
    output = Path(output_path).resolve()
    if output.suffix.lower() != ".slx":
        raise ValueError("blueprint output path must end in .slx")
    if output.exists() and not overwrite:
        raise ValueError(f"blueprint output already exists: {output}")
    output.parent.mkdir(parents=True, exist_ok=True)
    by_id = {item.id: item for item in document.blocks}
    request = {
        "kind": "slx-model-blueprint-build",
        "schema_version": document.schema_version,
        "model_name": document.model_name,
        "output_model": str(output),
        "blocks": [
            {
                "id": item.id,
                "library": BLOCK_CATALOG[item.type].library,
                "name": item.name,
                "position": list(item.position),
                "parameters": dict(item.parameters),
            }
            for item in document.blocks
        ],
        "connections": [
            {
                "src_name": by_id[item.src].name,
                "dst_name": by_id[item.dst].name,
                "src_port": item.src_port,
                "dst_port": item.dst_port,
                "name": item.name,
            }
            for item in document.connections
        ],
        "model_parameters": dict(document.model_parameters),
    }
    return _run_blueprint_matlab_request(request, matlab=matlab, timeout=timeout)


def _edit_runner_source(request_path: Path, result_path: Path) -> str:
    request = _matlab_quote(str(request_path.resolve()))
    result = _matlab_quote(str(result_path.resolve()))
    return f"""% Generated by SLX Studio for a validated structural edit.
requestPath = '{request}';
resultPath = '{result}';
result = struct('ok', false, 'message', '', 'output_model', '');
loadedName = '';
try
    req = jsondecode(fileread(requestPath));
    inputPath = char(req.input_model);
    outputPath = char(req.output_model);
    h = load_system(inputPath);
    loadedName = get_param(h, 'Name');
    ops = req.edit.operations;
    if ~isempty(ops)
        if iscell(ops), ops = [ops{{:}}]; end
        for k = 1:numel(ops)
            op = ops(k);
            kind = char(op.op);
            if strcmp(kind, 'set_param')
                target = loadedName;
                rel = char(op.block_path);
                if ~isempty(rel), target = [loadedName '/' rel]; end
                parameter = char(op.parameter);
                expected = char(op.before);
                desired = char(op.after);
                current = get_param(target, parameter);
                if isnumeric(current), current = mat2str(current); end
                if isstring(current), current = char(current); end
                if ~ischar(current), current = char(string(current)); end
                if ~strcmp(current, expected)
                    error('slxstudio:EditConflict', 'Parameter conflict at %s/%s', target, parameter);
                end
                set_param(target, parameter, desired);
            elseif strcmp(kind, 'add_block')
                parent = char(op.parent);
                destination = [loadedName '/' char(op.name)];
                if ~isempty(parent), destination = [loadedName '/' parent '/' char(op.name)]; end
                add_block(char(op.library), destination);
                set_param(destination, 'Position', double(op.position(:)'));
                if isfield(op, 'parameters')
                    names = fieldnames(op.parameters);
                    for p = 1:numel(names)
                        parameter = names{{p}};
                        value = op.parameters.(parameter);
                        if isnumeric(value), value = mat2str(value); end
                        if isstring(value), value = char(value); end
                        if ~ischar(value), value = char(string(value)); end
                        set_param(destination, parameter, value);
                    end
                end
            elseif strcmp(kind, 'delete_block')
                delete_block([loadedName '/' char(op.block_path)]);
            elseif strcmp(kind, 'rename_block')
                set_param([loadedName '/' char(op.block_path)], 'Name', char(op.new_name));
            elseif strcmp(kind, 'move_block')
                target = [loadedName '/' char(op.block_path)];
                current = double(get_param(target, 'Position'));
                expected = double(op.before_position(:)');
                desired = double(op.position(:)');
                if numel(current) ~= 4 || any(current ~= expected)
                    error('slxstudio:EditConflict', 'Position conflict at %s', target);
                end
                set_param(target, 'Position', desired);
            elseif strcmp(kind, 'add_line') || strcmp(kind, 'delete_line')
                systemName = loadedName;
                relSystem = char(op.system_path);
                if ~isempty(relSystem), systemName = [loadedName '/' relSystem]; end
                src = [char(op.src_local) '/' num2str(double(op.src_port))];
                dst = [char(op.dst_local) '/' num2str(double(op.dst_port))];
                if strcmp(kind, 'add_line')
                    add_line(systemName, src, dst, 'autorouting', 'on');
                else
                    delete_line(systemName, src, dst);
                end
            else
                error('slxstudio:UnsupportedEdit', 'Unsupported edit operation: %s', kind);
            end
        end
    end
    save_system(loadedName, outputPath);
    result.ok = true;
    result.message = 'Model edit applied successfully';
    result.output_model = outputPath;
catch ME
    result.ok = false;
    result.message = ME.message;
    result.identifier = ME.identifier;
end
try
    if ~isempty(loadedName), close_system(loadedName, 0); end
catch
end
fid = fopen(resultPath, 'w');
fprintf(fid, '%s', jsonencode(result));
fclose(fid);
if ~result.ok
    error('slxstudio:EditFailed', '%s', result.message);
end
"""


def apply_model_edit_with_matlab(
    model_path: str | Path,
    edit,
    *,
    output_path: str | Path | None = None,
    matlab: str | Path | None = None,
    timeout: float = 300.0,
) -> dict[str, Any]:
    from .blueprint import BLOCK_CATALOG
    from .model_edit import ModelEditDocument, edit_document_from_dict, validate_edit_document

    source = Path(model_path).resolve()
    document = edit if isinstance(edit, ModelEditDocument) else edit_document_from_dict(edit)
    model = parse_slx(source)
    validate_edit_document(document, model, source_path=source)
    output = Path(output_path).resolve() if output_path is not None else source
    output.parent.mkdir(parents=True, exist_ok=True)

    operations: list[dict[str, Any]] = []
    for raw in document.operations:
        op = dict(raw)
        if op["op"] == "add_block":
            op["library"] = BLOCK_CATALOG[op["block_type"]].library
        elif op["op"] in {"add_line", "delete_line"}:
            system_path = op.get("system_path", "")
            op["src_local"] = relative_to_system(op["src_path"], system_path)
            op["dst_local"] = relative_to_system(op["dst_path"], system_path)
        operations.append(op)

    request = {
        "input_model": str(source),
        "output_model": str(output),
        "edit": {**document.to_dict(), "operations": operations},
    }
    status = find_matlab(matlab)
    if not status.available or not status.executable:
        raise RuntimeError(status.detail)
    with tempfile.TemporaryDirectory(prefix="slx-studio-edit-") as temp_dir:
        root = Path(temp_dir)
        request_path = root / "request.json"
        result_path = root / "result.json"
        runner_path = root / "apply_slx_edit.m"
        request_path.write_text(json.dumps(request, ensure_ascii=False), encoding="utf-8")
        runner_path.write_text(_edit_runner_source(request_path, result_path), encoding="utf-8")
        batch = f"run('{_matlab_quote(str(runner_path.resolve()))}')"
        proc = subprocess.run(
            [*_matlab_command(status.executable), "-batch", batch],
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
        if not result_path.exists():
            detail = (proc.stderr or proc.stdout or "MATLAB exited without an edit result").strip()
            raise RuntimeError(detail)
        try:
            result = json.loads(result_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise RuntimeError(f"MATLAB edit bridge returned invalid JSON: {exc}") from exc
        if proc.returncode != 0 or not result.get("ok"):
            raise RuntimeError(
                str(result.get("message") or proc.stderr or proc.stdout or "MATLAB model edit failed").strip()
            )
        return result


def create_empty_model_with_matlab(
    output_path: str | Path,
    *,
    matlab: str | Path | None = None,
    timeout: float = 180.0,
) -> dict[str, Any]:
    output = Path(output_path).resolve()
    if output.suffix.lower() != ".slx":
        raise ValueError("new Simulink model name must end in .slx")
    if output.exists():
        raise ValueError(f"file already exists: {output}")
    name = output.stem
    if not name or not name[0].isalpha() or not all(ch.isalnum() or ch == "_" for ch in name):
        raise ValueError(
            "Simulink model file name must start with a letter and use only letters, digits, or underscores"
        )
    status = find_matlab(matlab)
    if not status.available or not status.executable:
        raise RuntimeError(status.detail)
    output.parent.mkdir(parents=True, exist_ok=True)
    expression = (
        f"new_system('{_matlab_quote(name)}'); "
        f"save_system('{_matlab_quote(name)}','{_matlab_quote(str(output))}'); "
        f"close_system('{_matlab_quote(name)}',0)"
    )
    proc = subprocess.run(
        [*_matlab_command(status.executable), "-batch", expression],
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
    )
    if proc.returncode != 0 or not output.exists():
        raise RuntimeError((proc.stderr or proc.stdout or "MATLAB failed to create the model").strip())
    return {"ok": True, "output_model": str(output), "stdout": proc.stdout or "", "stderr": proc.stderr or ""}
