from __future__ import annotations

import base64
import json
import subprocess
import tempfile
import threading
import time
import uuid
from collections.abc import Callable
from pathlib import Path
from typing import Any

from .matlab_bridge import _matlab_command, _matlab_quote, find_matlab

_MAX_FIGURES = 6
_MAX_FIGURE_BYTES = 3 * 1024 * 1024
_MAX_RETAINED_JOBS = 100
_JOB_RETENTION_SECONDS = 60 * 60


def _runner_source(
    executable_script: Path,
    result_path: Path,
    figure_dir: Path,
    *,
    source_path: Path,
    line_offset: int = 0,
    workspace_file: Path | None = None,
) -> str:
    script_q = _matlab_quote(str(executable_script.resolve()))
    source_q = _matlab_quote(str(source_path.resolve()))
    result_q = _matlab_quote(str(result_path.resolve()))
    parent_q = _matlab_quote(str(source_path.parent.resolve()))
    figure_q = _matlab_quote(str(figure_dir.resolve()))
    workspace_q = _matlab_quote(str(Path(workspace_file).resolve())) if workspace_file is not None else ""
    run_expression_q = _matlab_quote(f"run('{script_q}')")
    return f"""% Generated by SLX Studio. User code executes in the MATLAB base workspace.
% Debug metadata (comments only):
% scriptPath = '{script_q}';
% sourcePath = '{source_q}';
% resultPath = '{result_q}';
% figureDir = '{figure_q}';
% workspaceFile = '{workspace_q}';
% lineOffset = {int(line_offset)};
result = slxstudio_execute_script('{script_q}', '{source_q}', {int(line_offset)}, '{figure_q}', '{workspace_q}', '{parent_q}', '{run_expression_q}');
fid = fopen('{result_q}', 'w');
if fid ~= -1
    fprintf(fid, '%s', jsonencode(result));
    fclose(fid);
end
if ~result.ok
    if isfield(result, 'error') && isfield(result.error, 'message')
        error('slxstudio:ScriptFailed', '%s', char(result.error.message));
    else
        error('slxstudio:ScriptFailed', 'MATLAB script failed');
    end
end

function result = slxstudio_execute_script(scriptPath, sourcePath, lineOffset, figureDir, workspaceFile, workDir, runExpression)
result = struct('ok', true, 'variables', [], 'figures', [], 'error', struct());
try
    cd(workDir);
    slxstudio_restore_base_workspace(workspaceFile);
    evalin('base', runExpression);
catch ME
    result.ok = false;
    result.error = slxstudio_error_struct(ME, scriptPath, sourcePath, lineOffset);
end
raw = evalin('base', 'whos');
vars = struct('name', {{}}, 'class', {{}}, 'size', {{}}, 'bytes', {{}}, 'preview', {{}});
idx = 0;
for k = 1:numel(raw)
    if ~isvarname(raw(k).name), continue; end
    idx = idx + 1;
    item = struct();
    item.name = raw(k).name;
    item.class = raw(k).class;
    item.size = sprintf('%dx', raw(k).size);
    if ~isempty(item.size), item.size = item.size(1:end-1); end
    item.bytes = raw(k).bytes;
    item.preview = '';
    try
        value = evalin('base', raw(k).name);
        if (isnumeric(value) || islogical(value)) && isscalar(value)
            item.preview = char(string(value));
        elseif ischar(value) && numel(value) <= 160
            item.preview = value;
        elseif isstring(value) && isscalar(value) && strlength(value) <= 160
            item.preview = char(value);
        end
    catch
    end
    vars(idx) = item; %#ok<AGROW>
end
result.variables = vars;
result.figures = slxstudio_export_figures(figureDir);
try
    slxstudio_save_base_workspace(workspaceFile, raw);
catch
end
end

function slxstudio_restore_base_workspace(workspaceFile)
evalin('base', 'clearvars');
if isempty(workspaceFile) || ~exist(workspaceFile, 'file'), return; end
try
    state = load(workspaceFile);
    names = fieldnames(state);
    for k = 1:numel(names)
        name = names{{k}};
        if isvarname(name), assignin('base', name, state.(name)); end
    end
catch
end
end

function slxstudio_save_base_workspace(workspaceFile, raw)
if isempty(workspaceFile), return; end
state = struct();
for k = 1:numel(raw)
    name = raw(k).name;
    if ~isvarname(name), continue; end
    try, state.(name) = evalin('base', name); catch, end
end
names = fieldnames(state);
if isempty(names)
    if exist(workspaceFile, 'file'), delete(workspaceFile); end
else
    save(workspaceFile, '-struct', 'state');
end
end

function figs = slxstudio_export_figures(figureDir)
figs = struct('name', {{}}, 'path', {{}});
try
    if ~exist(figureDir, 'dir'), mkdir(figureDir); end
    handles = findall(groot, 'Type', 'figure');
    handles = flipud(handles(:));
    maxFigures = min(numel(handles), {_MAX_FIGURES});
    for k = 1:maxFigures
        fig = handles(k);
        filePath = fullfile(figureDir, sprintf('figure-%02d.png', k));
        try
            exportgraphics(fig, filePath, 'Resolution', 120);
        catch
            try
                print(fig, filePath, '-dpng', '-r120');
            catch
                continue;
            end
        end
        label = sprintf('Figure %d', k);
        try
            figName = get(fig, 'Name');
            if ~isempty(figName), label = char(figName); end
        catch
        end
        figs(end+1) = struct('name', label, 'path', filePath); %#ok<AGROW>
    end
catch
end
end

function e = slxstudio_error_struct(ME, scriptPath, sourcePath, lineOffset)
e = struct('message', ME.message, 'identifier', ME.identifier, 'line', 0, 'file', '');
try
    if ~isempty(ME.stack)
        e.line = ME.stack(1).line;
        e.file = ME.stack(1).file;
        if strcmp(char(e.file), char(scriptPath))
            e.line = e.line + lineOffset;
            e.file = sourcePath;
        end
    end
catch
end
end
"""


def _normalize_variables(value: Any) -> list[dict[str, Any]]:
    if value is None or value == []:
        return []
    items = value if isinstance(value, list) else [value]
    result: list[dict[str, Any]] = []
    for raw in items:
        if not isinstance(raw, dict) or not raw.get("name"):
            continue
        result.append(
            {
                "name": str(raw.get("name", "")),
                "class": str(raw.get("class", "")),
                "size": str(raw.get("size", "")),
                "bytes": int(raw.get("bytes") or 0),
                "preview": str(raw.get("preview", "")),
            }
        )
    return result


def _normalize_figures(value: Any, root: Path) -> list[dict[str, Any]]:
    items = value if isinstance(value, list) else ([value] if isinstance(value, dict) and value else [])
    figures: list[dict[str, Any]] = []
    for raw in items[:_MAX_FIGURES]:
        if not isinstance(raw, dict):
            continue
        path_text = str(raw.get("path", ""))
        if not path_text:
            continue
        path = Path(path_text)
        try:
            resolved = path.resolve()
            resolved.relative_to(root.resolve())
            size = resolved.stat().st_size
        except (OSError, ValueError):
            continue
        if size <= 0 or size > _MAX_FIGURE_BYTES:
            continue
        data = base64.b64encode(resolved.read_bytes()).decode("ascii")
        figures.append(
            {
                "name": str(raw.get("name") or f"Figure {len(figures) + 1}"),
                "mime": "image/png",
                "bytes": size,
                "data_base64": data,
            }
        )
    return figures


def _prepare_execution(
    script: Path,
    root: Path,
    *,
    code: str | None,
    start_line: int,
    workspace_file: Path | None = None,
) -> tuple[Path, Path, Path, int]:
    result_path = root / "result.json"
    figure_dir = root / "figures"
    if code is None:
        executable = script
        offset = 0
    else:
        if len(code.encode("utf-8")) > 4 * 1024 * 1024:
            raise ValueError("MATLAB section is too large")
        executable = root / "slxstudio_section.m"
        executable.write_text(code, encoding="utf-8")
        offset = max(0, int(start_line) - 1)
    runner_path = root / "run_slxstudio_script.m"
    runner_path.write_text(
        _runner_source(
            executable,
            result_path,
            figure_dir,
            source_path=script,
            line_offset=offset,
            workspace_file=workspace_file,
        ),
        encoding="utf-8",
    )
    return runner_path, result_path, figure_dir, offset


def _result_from_process(
    script: Path,
    proc: subprocess.Popen[str],
    result_path: Path,
    figure_dir: Path,
    root: Path,
    started: float,
    *,
    cancelled: bool,
    stdout: str,
    stderr: str,
) -> dict[str, Any]:
    metadata: dict[str, Any] = {}
    if result_path.exists():
        try:
            parsed = json.loads(result_path.read_text(encoding="utf-8"))
            if isinstance(parsed, dict):
                metadata = parsed
        except json.JSONDecodeError:
            metadata = {}
    elapsed = time.perf_counter() - started
    bridge_ok = bool(metadata.get("ok", proc.returncode == 0))
    error = metadata.get("error") if isinstance(metadata.get("error"), dict) else {}
    return {
        "ok": proc.returncode == 0 and bridge_ok and not cancelled,
        "cancelled": bool(cancelled),
        "path": str(script),
        "returncode": proc.returncode,
        "elapsed_seconds": elapsed,
        "stdout": stdout or "",
        "stderr": stderr or "",
        "variables": _normalize_variables(metadata.get("variables")),
        "figures": _normalize_figures(metadata.get("figures"), root),
        "error": {
            "message": str(error.get("message", "")),
            "identifier": str(error.get("identifier", "")),
            "line": int(error.get("line") or 0),
            "file": str(error.get("file", "")),
        }
        if error
        else None,
    }


def _run_m(
    path: str | Path,
    *,
    matlab: str | Path | None,
    timeout: float,
    code: str | None = None,
    start_line: int = 1,
    on_process: Callable[[subprocess.Popen[str]], None] | None = None,
    cancelled: Callable[[], bool] | None = None,
    workspace_file: str | Path | None = None,
) -> dict[str, Any]:
    script = Path(path).resolve()
    if not script.exists() or script.suffix.lower() != ".m":
        raise ValueError("MATLAB runner requires an existing .m file")
    status = find_matlab(matlab)
    if not status.available or not status.executable:
        raise RuntimeError(status.detail)

    started = time.perf_counter()
    with tempfile.TemporaryDirectory(prefix="slx-studio-m-run-") as temp_dir:
        root = Path(temp_dir)
        checkpoint = Path(workspace_file).resolve() if workspace_file is not None else None
        if checkpoint is not None:
            checkpoint.parent.mkdir(parents=True, exist_ok=True)
        runner_path, result_path, figure_dir, _ = _prepare_execution(
            script, root, code=code, start_line=start_line, workspace_file=checkpoint
        )
        expression = f"run('{_matlab_quote(str(runner_path.resolve()))}')"
        proc = subprocess.Popen(
            [*_matlab_command(status.executable), "-batch", expression],
            cwd=script.parent,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        if on_process:
            on_process(proc)
        was_cancelled = False
        try:
            stdout, stderr = proc.communicate(timeout=timeout)
        except subprocess.TimeoutExpired as exc:
            proc.kill()
            stdout, stderr = proc.communicate()
            raise RuntimeError(f"MATLAB run timed out after {timeout:g} seconds") from exc
        if cancelled:
            was_cancelled = bool(cancelled())
        return _result_from_process(
            script,
            proc,
            result_path,
            figure_dir,
            root,
            started,
            cancelled=was_cancelled,
            stdout=stdout,
            stderr=stderr,
        )


def run_m_file(
    path: str | Path,
    *,
    matlab: str | Path | None = None,
    timeout: float = 300.0,
    workspace_file: str | Path | None = None,
) -> dict[str, Any]:
    return _run_m(path, matlab=matlab, timeout=timeout, workspace_file=workspace_file)


def run_m_code(
    path: str | Path,
    code: str,
    *,
    start_line: int = 1,
    matlab: str | Path | None = None,
    timeout: float = 300.0,
    workspace_file: str | Path | None = None,
) -> dict[str, Any]:
    if not isinstance(code, str) or not code.strip():
        raise ValueError("MATLAB section code must be a non-empty string")
    return _run_m(
        path, matlab=matlab, timeout=timeout, code=code, start_line=start_line, workspace_file=workspace_file
    )


class MatlabRunManager:
    """One-session asynchronous MATLAB job manager used by the desktop Workbench."""

    def __init__(
        self,
        *,
        matlab: str | Path | None = None,
        timeout: float = 300.0,
        workspace_file: str | Path | None = None,
        execution_lock: threading.RLock | None = None,
    ):
        self.matlab = matlab
        self.timeout = timeout
        self.workspace_file = Path(workspace_file).resolve() if workspace_file is not None else None
        self.execution_lock = execution_lock or threading.RLock()
        self._lock = threading.RLock()
        self._jobs: dict[str, dict[str, Any]] = {}
        self._active_job: str | None = None

    def _prune_jobs_locked(self) -> None:
        """Bound completed-job memory while never removing a running job."""
        now = time.time()
        completed = [
            (job_id, job)
            for job_id, job in self._jobs.items()
            if job.get("state") != "running" and job.get("finished_at")
        ]
        expired = {
            job_id
            for job_id, job in completed
            if now - float(job.get("finished_at") or now) > _JOB_RETENTION_SECONDS
        }
        keep = sorted(completed, key=lambda item: float(item[1].get("finished_at") or 0), reverse=True)[
            :_MAX_RETAINED_JOBS
        ]
        keep_ids = {job_id for job_id, _ in keep}
        for job_id, _ in completed:
            if job_id in expired or (len(completed) > _MAX_RETAINED_JOBS and job_id not in keep_ids):
                self._jobs.pop(job_id, None)

    def start(self, path: str | Path, *, code: str | None = None, start_line: int = 1) -> dict[str, Any]:
        script = Path(path).resolve()
        if not script.exists() or script.suffix.lower() != ".m":
            raise ValueError("MATLAB runner requires an existing .m file")
        status = find_matlab(self.matlab)
        if not status.available:
            raise RuntimeError(status.detail)
        with self._lock:
            self._prune_jobs_locked()
            if self._active_job:
                active = self._jobs.get(self._active_job)
                if active and active.get("state") == "running":
                    raise RuntimeError("a MATLAB run is already active")
            job_id = uuid.uuid4().hex
            job: dict[str, Any] = {
                "id": job_id,
                "path": str(script),
                "state": "running",
                "started_at": time.time(),
                "process": None,
                "cancel_requested": False,
                "result": None,
                "error": None,
            }
            self._jobs[job_id] = job
            self._active_job = job_id

        def set_process(proc: subprocess.Popen[str]) -> None:
            with self._lock:
                job["process"] = proc
                if job.get("cancel_requested") and proc.poll() is None:
                    proc.terminate()

        def worker() -> None:
            try:
                with self.execution_lock:
                    if job.get("cancel_requested"):
                        result = {
                            "ok": False,
                            "cancelled": True,
                            "stdout": "",
                            "stderr": "",
                            "variables": [],
                            "figures": [],
                        }
                    else:
                        result = _run_m(
                            script,
                            matlab=self.matlab,
                            timeout=self.timeout,
                            code=code,
                            start_line=start_line,
                            on_process=set_process,
                            cancelled=lambda: bool(job.get("cancel_requested")),
                            workspace_file=self.workspace_file,
                        )
                with self._lock:
                    job["result"] = result
                    job["state"] = "cancelled" if result.get("cancelled") else "finished"
            except Exception as exc:  # noqa: BLE001 - background worker must surface failures through status
                with self._lock:
                    job["error"] = str(exc)
                    job["state"] = "cancelled" if job.get("cancel_requested") else "failed"
            finally:
                with self._lock:
                    job["process"] = None
                    job["finished_at"] = time.time()
                    if self._active_job == job_id:
                        self._active_job = None

        threading.Thread(target=worker, name=f"slxstudio-matlab-{job_id[:8]}", daemon=True).start()
        return self.status(job_id)

    def status(self, job_id: str) -> dict[str, Any]:
        with self._lock:
            self._prune_jobs_locked()
            job = self._jobs.get(str(job_id))
            if not job:
                raise ValueError("unknown MATLAB run job")
            payload = {
                "id": job["id"],
                "path": job["path"],
                "state": job["state"],
                "started_at": job["started_at"],
            }
            if job.get("finished_at"):
                payload["finished_at"] = job["finished_at"]
            if job.get("result") is not None:
                payload["result"] = job["result"]
            if job.get("error"):
                payload["error"] = job["error"]
            return payload

    def stop(self, job_id: str) -> dict[str, Any]:
        with self._lock:
            job = self._jobs.get(str(job_id))
            if not job:
                raise ValueError("unknown MATLAB run job")
            if job.get("state") != "running":
                return self.status(job_id)
            job["cancel_requested"] = True
            proc = job.get("process")
            if isinstance(proc, subprocess.Popen) and proc.poll() is None:
                try:
                    proc.terminate()
                    proc.wait(timeout=2.0)
                except subprocess.TimeoutExpired:
                    proc.kill()
                except OSError:
                    pass
            return self.status(job_id)

    def stop_all(self) -> None:
        with self._lock:
            ids = [job_id for job_id, job in self._jobs.items() if job.get("state") == "running"]
        for job_id in ids:
            try:
                self.stop(job_id)
            except (ValueError, OSError):
                pass
