from __future__ import annotations

import json
import re
import subprocess
import tempfile
import threading
import time
from pathlib import Path
from typing import Any

from .matlab_bridge import _matlab_quote, find_matlab
from .mrunner import _normalize_figures, _normalize_variables

_IDENTIFIER = re.compile(r"^[A-Za-z]\w*$")
_MAX_COMMAND_BYTES = 256 * 1024


def _command_runner_source(
    result_path: Path,
    figure_dir: Path,
    workspace_file: Path,
    *,
    command: str,
    work_dir: Path,
) -> str:
    result_q = _matlab_quote(str(result_path.resolve()))
    figure_q = _matlab_quote(str(figure_dir.resolve()))
    workspace_q = _matlab_quote(str(workspace_file.resolve()))
    work_q = _matlab_quote(str(work_dir.resolve()))
    command_bytes = " ".join(str(value) for value in command.encode("utf-8"))
    command_expr = f"native2unicode(uint8([{command_bytes}]), 'UTF-8')"
    return f"""% Generated by SLX Studio Command Window. User commands execute in the MATLAB base workspace.
% Debug metadata (comments only):
% resultPath = '{result_q}';
% figureDir = '{figure_q}';
% workspaceFile = '{workspace_q}';
% workDir = '{work_q}';
result = slxstudio_execute_command('{figure_q}', '{workspace_q}', '{work_q}', {command_expr});
fid = fopen('{result_q}', 'w');
if fid ~= -1, fprintf(fid, '%s', jsonencode(result)); fclose(fid); end
if ~result.ok, error('slxstudio:CommandFailed', '%s', char(result.error.message)); end

function result = slxstudio_execute_command(figureDir, workspaceFile, workDir, commandText)
result = struct('ok', false, 'stdout', '', 'variables', [], 'figures', [], 'error', struct());
try
    cd(workDir);
    slxstudio_restore_base_workspace(workspaceFile);
    result.stdout = evalc('evalin(''base'', commandText)');
    result.ok = true;
catch ME
    result.ok = false;
    result.error = struct('message', ME.message, 'identifier', ME.identifier, 'line', 0, 'file', '');
    try
        if ~isempty(ME.stack)
            result.error.line = ME.stack(1).line;
            result.error.file = ME.stack(1).file;
        end
    catch
    end
end
raw = evalin('base', 'whos');
vars = struct('name', {{}}, 'class', {{}}, 'size', {{}}, 'bytes', {{}}, 'preview', {{}});
idx = 0;
for k = 1:numel(raw)
    if ~isvarname(raw(k).name), continue; end
    idx = idx + 1;
    item = struct('name', raw(k).name, 'class', raw(k).class, 'size', '', 'bytes', raw(k).bytes, 'preview', '');
    item.size = sprintf('%dx', raw(k).size); if ~isempty(item.size), item.size = item.size(1:end-1); end
    try
        value = evalin('base', raw(k).name);
        if (isnumeric(value) || islogical(value)) && isscalar(value)
            item.preview = char(string(value));
        elseif ischar(value) && numel(value) <= 160
            item.preview = value;
        elseif isstring(value) && isscalar(value) && strlength(value) <= 160
            item.preview = char(value);
        end
    catch
    end
    vars(idx) = item; %#ok<AGROW>
end
result.variables = vars;
try
    if ~exist(figureDir, 'dir'), mkdir(figureDir); end
    handles = flipud(findall(groot, 'Type', 'figure'));
    figs = struct('name', {{}}, 'path', {{}});
    for k = 1:min(numel(handles), 6)
        filePath = fullfile(figureDir, sprintf('figure-%02d.png', k));
        try
            exportgraphics(handles(k), filePath, 'Resolution', 120);
        catch
            try, print(handles(k), filePath, '-dpng', '-r120'); catch, continue; end
        end
        label = sprintf('Figure %d', k);
        try, n = get(handles(k), 'Name'); if ~isempty(n), label = char(n); end, catch, end
        figs(end+1) = struct('name', label, 'path', filePath); %#ok<AGROW>
    end
    result.figures = figs;
catch
end
try, slxstudio_save_base_workspace(workspaceFile, raw); catch, end
end

function slxstudio_restore_base_workspace(workspaceFile)
evalin('base', 'clearvars');
if ~exist(workspaceFile, 'file'), return; end
try
    state = load(workspaceFile);
    names = fieldnames(state);
    for k = 1:numel(names)
        name = names{{k}};
        if isvarname(name), assignin('base', name, state.(name)); end
    end
catch
end
end

function slxstudio_save_base_workspace(workspaceFile, raw)
state = struct();
for k = 1:numel(raw)
    name = raw(k).name;
    if ~isvarname(name), continue; end
    try, state.(name) = evalin('base', name); catch, end
end
names = fieldnames(state);
if isempty(names)
    if exist(workspaceFile, 'file'), delete(workspaceFile); end
else
    save(workspaceFile, '-struct', 'state');
end
end
"""


class MatlabCommandSession:
    """Project-scoped MATLAB command session persisted through a temporary MAT workspace file."""

    def __init__(
        self,
        *,
        work_dir: str | Path,
        workspace_file: str | Path,
        matlab: str | Path | None = None,
        timeout: float = 120.0,
        execution_lock: threading.RLock | None = None,
    ) -> None:
        self.work_dir = Path(work_dir).resolve()
        self.workspace_file = Path(workspace_file).resolve()
        self.matlab = matlab
        self.timeout = timeout
        self.execution_lock = execution_lock or threading.RLock()

    def execute(self, command: str) -> dict[str, Any]:
        if not isinstance(command, str) or not command.strip():
            raise ValueError("MATLAB command must be non-empty")
        if len(command.encode("utf-8")) > _MAX_COMMAND_BYTES:
            raise ValueError("MATLAB command is too large")
        status = find_matlab(self.matlab)
        if not status.available or not status.executable:
            raise RuntimeError(status.detail)
        with self.execution_lock:
            self.workspace_file.parent.mkdir(parents=True, exist_ok=True)
            started = time.perf_counter()
            with tempfile.TemporaryDirectory(prefix="slx-studio-command-") as temp_dir:
                root = Path(temp_dir)
                result_path = root / "result.json"
                figure_dir = root / "figures"
                runner = root / "run_slxstudio_command.m"
                runner.write_text(
                    _command_runner_source(
                        result_path,
                        figure_dir,
                        self.workspace_file,
                        command=command,
                        work_dir=self.work_dir,
                    ),
                    encoding="utf-8",
                )
                batch = f"run('{_matlab_quote(str(runner.resolve()))}')"
                proc = subprocess.run(
                    [status.executable, "-batch", batch],
                    cwd=self.work_dir,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    timeout=self.timeout,
                    check=False,
                )
                metadata: dict[str, Any] = {}
                if result_path.exists():
                    try:
                        raw = json.loads(result_path.read_text(encoding="utf-8"))
                        if isinstance(raw, dict):
                            metadata = raw
                    except json.JSONDecodeError:
                        metadata = {}
                error = metadata.get("error") if isinstance(metadata.get("error"), dict) else {}
                result = {
                    "ok": proc.returncode == 0 and bool(metadata.get("ok", proc.returncode == 0)),
                    "command": command,
                    "elapsed_seconds": time.perf_counter() - started,
                    "stdout": str(metadata.get("stdout") or proc.stdout or ""),
                    "stderr": proc.stderr or "",
                    "variables": _normalize_variables(metadata.get("variables")),
                    "figures": _normalize_figures(metadata.get("figures"), root),
                    "error": {
                        "message": str(error.get("message", "")),
                        "identifier": str(error.get("identifier", "")),
                        "line": int(error.get("line") or 0),
                        "file": str(error.get("file", "")),
                    } if error else None,
                }
                if not result["ok"] and not result["error"]:
                    result["error"] = {"message": (proc.stderr or proc.stdout or "MATLAB command failed").strip(), "identifier": "", "line": 0, "file": ""}
                return result

    def set_variable(self, name: str, expression: str) -> dict[str, Any]:
        if not _IDENTIFIER.fullmatch(str(name or "")):
            raise ValueError("variable name must be a MATLAB identifier")
        if not isinstance(expression, str) or not expression.strip():
            raise ValueError("variable expression must be non-empty")
        if "\n" in expression or "\r" in expression:
            raise ValueError("variable editor accepts one MATLAB expression")
        result = self.execute(f"{name} = {expression};")
        result["variable"] = name
        return result
