from __future__ import annotations

import json
import math
import subprocess
import tempfile
import threading
import time
import uuid
from collections.abc import Callable
from pathlib import Path
from typing import Any

from .matlab_bridge import _matlab_command, _matlab_quote, find_matlab, validate_simulation_stop_time
from .parser import parse_slx

_MAX_SWEEP_VALUES = 20
_MAX_RETAINED_JOBS = 100
_JOB_RETENTION_SECONDS = 60 * 60


def parse_sweep_values(value: str | list[Any] | tuple[Any, ...]) -> list[str]:
    if isinstance(value, (list, tuple)):
        items = [str(item).strip() for item in value]
    else:
        text = str(value or "").strip()
        if not text:
            raise ValueError("sweep values are required")
        if ":" in text and "," not in text:
            parts = [part.strip() for part in text.split(":")]
            if len(parts) not in {2, 3}:
                raise ValueError("range syntax must be start:end or start:step:end")
            try:
                start = float(parts[0])
                if len(parts) == 2:
                    end = float(parts[1])
                    step = 1.0 if end >= start else -1.0
                else:
                    step = float(parts[1])
                    end = float(parts[2])
            except ValueError as exc:
                raise ValueError("sweep range must contain numeric values") from exc
            if not all(math.isfinite(item) for item in (start, step, end)) or step == 0:
                raise ValueError("invalid sweep range")
            if (end - start) * step < 0:
                raise ValueError("sweep step moves away from the end value")
            numeric: list[float] = []
            current = start
            tolerance = abs(step) * 1e-9 + 1e-12
            while current <= end + tolerance if step > 0 else current >= end - tolerance:
                numeric.append(current)
                if len(numeric) > _MAX_SWEEP_VALUES:
                    raise ValueError(f"sweep supports at most {_MAX_SWEEP_VALUES} values")
                current = start + step * len(numeric)
            items = [format(item, ".12g") for item in numeric]
        else:
            items = [item.strip() for item in text.split(",")]
    items = [item for item in items if item]
    if not items:
        raise ValueError("sweep values are required")
    if len(items) > _MAX_SWEEP_VALUES:
        raise ValueError(f"sweep supports at most {_MAX_SWEEP_VALUES} values")
    normalized: list[str] = []
    for item in items:
        if len(item) > 128 or "\n" in item or "\r" in item:
            raise ValueError("invalid sweep value")
        try:
            numeric = float(item)
        except ValueError as exc:
            raise ValueError("sweep values must be finite numeric scalars") from exc
        if not math.isfinite(numeric):
            raise ValueError("sweep values must be finite numeric scalars")
        normalized.append(format(numeric, ".12g"))
    return normalized


def validate_sweep(
    model_path: str | Path, block_path: str, parameter: str, values: list[str]
) -> dict[str, Any]:
    model = parse_slx(model_path)
    matches = [block for block in model.blocks.values() if block.path == block_path]
    if not matches:
        raise ValueError(f"block not found: {block_path}")
    block = matches[0]
    if parameter not in block.parameters:
        raise ValueError(f"parameter not found on {block_path}: {parameter}")
    return {
        "model": model.name,
        "block_path": block.path,
        "block_type": block.block_type,
        "parameter": parameter,
        "before": str(block.parameters.get(parameter, "")),
        "values": values,
    }


def _sweep_runner_source(request_path: Path, result_path: Path) -> str:
    request_q = _matlab_quote(str(request_path.resolve()))
    result_q = _matlab_quote(str(result_path.resolve()))
    return f"""% Generated by SLX Studio parameter sweep. Does not save the model.
requestPath = '{request_q}';
resultPath = '{result_q}';
result = struct('ok', false, 'message', '', 'runs', [], 'elapsed_seconds', 0);
loadedName = '';
originalValue = '';
startedAll = tic;
try
    req = jsondecode(fileread(requestPath));
    h = load_system(char(req.input_model));
    loadedName = get_param(h, 'Name');
    target = [loadedName '/' char(req.block_path)];
    parameter = char(req.parameter);
    originalValue = get_param(target, parameter);
    if isnumeric(originalValue), originalValue = mat2str(originalValue); end
    if isstring(originalValue), originalValue = char(originalValue); end
    if ~ischar(originalValue), originalValue = char(string(originalValue)); end
    values = req.values; if ~iscell(values), values = cellstr(string(values)); end
    runs = struct('value', {{}}, 'elapsed_seconds', {{}}, 'series', {{}});
    for k = 1:numel(values)
        desired = char(string(values{{k}}));
        set_param(target, parameter, desired);
        started = tic;
        simOut = sim(loadedName, 'StopTime', char(req.stop_time), 'ReturnWorkspaceOutputs', 'on');
        elapsed = toc(started);
        series = slxstudio_collect_sim_series(simOut);
        runs(end+1) = struct('value', desired, 'elapsed_seconds', elapsed, 'series', series); %#ok<AGROW>
    end
    set_param(target, parameter, originalValue);
    result.ok = true;
    result.message = 'Parameter sweep complete';
    result.runs = runs;
    result.elapsed_seconds = toc(startedAll);
catch ME
    result.ok = false; result.message = ME.message; result.identifier = ME.identifier;
    try, if ~isempty(loadedName) && ~isempty(originalValue), set_param([loadedName '/' char(req.block_path)], char(req.parameter), originalValue); end, catch, end
end
try, if ~isempty(loadedName), close_system(loadedName, 0); end, catch, end
fid = fopen(resultPath, 'w'); if fid ~= -1, fprintf(fid, '%s', jsonencode(result)); fclose(fid); end
if ~result.ok, error('slxstudio:SweepFailed', '%s', result.message); end

function series = slxstudio_collect_sim_series(simOut)
series = struct('name', {{}}, 'time', {{}}, 'data', {{}});
try, names = who(simOut); catch, names = {{}}; end
for n = 1:numel(names)
    if numel(series) >= 6, break; end
    name = char(names{{n}});
    try, value = get(simOut, name); series = slxstudio_append_series(series, name, value); catch, end
end
end
function series = slxstudio_append_series(series, name, value)
if numel(series) >= 6, return; end
if isa(value, 'timeseries'), series = slxstudio_append_timeseries(series, name, value); return; end
try
    if isa(value, 'Simulink.SimulationData.Dataset')
        count = numElements(value);
        for j = 1:count
            if numel(series) >= 6, break; end
            element = value{{j}}; elementName = name;
            try, if ~isempty(element.Name), elementName = [name '/' char(element.Name)]; end, catch, end
            try, series = slxstudio_append_timeseries(series, elementName, element.Values); catch, end
        end
    end
catch
end
end
function series = slxstudio_append_timeseries(series, name, ts)
try
    if ~isa(ts, 'timeseries'), return; end
    time = double(ts.Time(:)); data = double(ts.Data(:));
    if isempty(time) || numel(time) ~= numel(data) || ~isreal(time) || ~isreal(data), return; end
    mask = isfinite(time) & isfinite(data); time = time(mask); data = data(mask); if isempty(time), return; end
    maxPoints = 600; if numel(time) > maxPoints, idx = unique(round(linspace(1,numel(time),maxPoints))); time=time(idx); data=data(idx); end
    series(end+1) = struct('name', char(name), 'time', time(:)', 'data', data(:)'); %#ok<AGROW>
catch
end
end
"""


def _series_metrics(series: dict[str, Any]) -> dict[str, float | None]:
    raw_data = series.get("data") if isinstance(series, dict) else None
    raw_time = series.get("time") if isinstance(series, dict) else None
    data = [float(x) for x in raw_data] if isinstance(raw_data, list) else []
    times = [float(x) for x in raw_time] if isinstance(raw_time, list) else []
    pairs = [(t, y) for t, y in zip(times, data) if math.isfinite(t) and math.isfinite(y)]
    if not pairs:
        return {"min": None, "max": None, "final": None, "rms": None, "settling_estimate": None}
    times = [p[0] for p in pairs]
    data = [p[1] for p in pairs]
    final = data[-1]
    rms = math.sqrt(sum(y * y for y in data) / len(data))
    span = max(data) - min(data)
    tolerance = max(abs(final) * 0.02, span * 0.02, 1e-12)
    settling: float | None = None
    for idx in range(len(data)):
        if all(abs(y - final) <= tolerance for y in data[idx:]):
            settling = times[idx]
            break
    return {"min": min(data), "max": max(data), "final": final, "rms": rms, "settling_estimate": settling}


def _normalize_runs(value: Any) -> list[dict[str, Any]]:
    items = value if isinstance(value, list) else ([value] if isinstance(value, dict) and value else [])
    runs: list[dict[str, Any]] = []
    for raw in items[:_MAX_SWEEP_VALUES]:
        if not isinstance(raw, dict):
            continue
        series_raw = raw.get("series")
        series_items = (
            series_raw
            if isinstance(series_raw, list)
            else ([series_raw] if isinstance(series_raw, dict) and series_raw else [])
        )
        series: list[dict[str, Any]] = []
        for item in series_items[:6]:
            if not isinstance(item, dict):
                continue
            t = item.get("time") if isinstance(item.get("time"), list) else []
            d = item.get("data") if isinstance(item.get("data"), list) else []
            clean = {"name": str(item.get("name", "signal")), "time": t[:600], "data": d[:600]}
            clean["metrics"] = _series_metrics(clean)
            series.append(clean)
        runs.append(
            {
                "value": str(raw.get("value", "")),
                "elapsed_seconds": float(raw.get("elapsed_seconds") or 0),
                "series": series,
            }
        )
    return runs


def run_parameter_sweep_with_matlab(
    model_path: str | Path,
    *,
    block_path: str,
    parameter: str,
    values: str | list[Any] | tuple[Any, ...],
    stop_time: str = "10",
    matlab: str | Path | None = None,
    timeout: float = 900.0,
    on_process: Callable[[subprocess.Popen[str]], None] | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> dict[str, Any]:
    source = Path(model_path).resolve()
    parsed_values = parse_sweep_values(values)
    validation = validate_sweep(source, block_path, parameter, parsed_values)
    stop_time = validate_simulation_stop_time(stop_time)
    status = find_matlab(matlab)
    if not status.available or not status.executable:
        raise RuntimeError(status.detail)
    request = {
        "input_model": str(source),
        "block_path": block_path,
        "parameter": parameter,
        "values": parsed_values,
        "stop_time": str(stop_time),
    }
    started = time.perf_counter()
    with tempfile.TemporaryDirectory(prefix="slx-studio-sweep-") as temp_dir:
        root = Path(temp_dir)
        request_path = root / "request.json"
        result_path = root / "result.json"
        runner_path = root / "run_slxstudio_sweep.m"
        request_path.write_text(json.dumps(request, ensure_ascii=False), encoding="utf-8")
        runner_path.write_text(_sweep_runner_source(request_path, result_path), encoding="utf-8")
        batch = f"run('{_matlab_quote(str(runner_path.resolve()))}')"
        proc = subprocess.Popen(
            [*_matlab_command(status.executable), "-batch", batch],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        if on_process:
            on_process(proc)
        try:
            stdout, stderr = proc.communicate(timeout=timeout)
        except subprocess.TimeoutExpired as exc:
            proc.kill()
            proc.communicate()
            raise RuntimeError(f"MATLAB parameter sweep timed out after {timeout:g} seconds") from exc
        was_cancelled = bool(cancelled()) if cancelled else False
        if was_cancelled and not result_path.exists():
            return {
                "ok": False,
                "cancelled": True,
                "validation": validation,
                "runs": [],
                "stdout": stdout or "",
                "stderr": stderr or "",
                "elapsed_seconds": time.perf_counter() - started,
            }
        if not result_path.exists():
            raise RuntimeError((stderr or stdout or "MATLAB exited without a sweep result").strip())
        try:
            raw = json.loads(result_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise RuntimeError(f"MATLAB sweep returned invalid JSON: {exc}") from exc
        if proc.returncode != 0 or not raw.get("ok"):
            if was_cancelled:
                return {
                    "ok": False,
                    "cancelled": True,
                    "validation": validation,
                    "runs": [],
                    "stdout": stdout or "",
                    "stderr": stderr or "",
                    "elapsed_seconds": time.perf_counter() - started,
                }
            raise RuntimeError(str(raw.get("message") or stderr or stdout or "MATLAB sweep failed").strip())
        return {
            "ok": True,
            "cancelled": False,
            "validation": validation,
            "stop_time": str(stop_time),
            "runs": _normalize_runs(raw.get("runs")),
            "stdout": stdout or "",
            "stderr": stderr or "",
            "elapsed_seconds": float(raw.get("elapsed_seconds") or (time.perf_counter() - started)),
            "metric_disclaimer": "Settling time is a simple 2% final-value estimate from returned samples, not a control-system verification result.",
        }


class SweepRunManager:
    def __init__(
        self,
        *,
        matlab: str | Path | None = None,
        timeout: float = 900.0,
        execution_lock: threading.RLock | None = None,
    ) -> None:
        self.matlab = matlab
        self.timeout = timeout
        self.execution_lock = execution_lock or threading.RLock()
        self._lock = threading.RLock()
        self._jobs: dict[str, dict[str, Any]] = {}
        self._active: str | None = None

    def _prune_jobs_locked(self) -> None:
        now = time.time()
        completed = [
            (job_id, job)
            for job_id, job in self._jobs.items()
            if job.get("state") != "running" and job.get("finished_at")
        ]
        expired = {
            job_id
            for job_id, job in completed
            if now - float(job.get("finished_at") or now) > _JOB_RETENTION_SECONDS
        }
        keep = sorted(completed, key=lambda item: float(item[1].get("finished_at") or 0), reverse=True)[
            :_MAX_RETAINED_JOBS
        ]
        keep_ids = {job_id for job_id, _ in keep}
        for job_id, _ in completed:
            if job_id in expired or (len(completed) > _MAX_RETAINED_JOBS and job_id not in keep_ids):
                self._jobs.pop(job_id, None)

    def start(
        self, path: str | Path, *, block_path: str, parameter: str, values: Any, stop_time: str = "10"
    ) -> dict[str, Any]:
        parsed = parse_sweep_values(values)
        validate_sweep(path, block_path, parameter, parsed)
        with self._lock:
            self._prune_jobs_locked()
            if self._active and self._jobs.get(self._active, {}).get("state") == "running":
                raise RuntimeError("a parameter sweep is already active")
            job_id = uuid.uuid4().hex
            job: dict[str, Any] = {
                "id": job_id,
                "path": str(Path(path).resolve()),
                "state": "running",
                "started_at": time.time(),
                "process": None,
                "cancel_requested": False,
                "result": None,
                "error": None,
            }
            self._jobs[job_id] = job
            self._active = job_id

        def set_process(proc: subprocess.Popen[str]) -> None:
            with self._lock:
                job["process"] = proc
                if job.get("cancel_requested") and proc.poll() is None:
                    proc.terminate()

        def worker() -> None:
            try:
                with self.execution_lock:
                    if job.get("cancel_requested"):
                        result = {"ok": False, "cancelled": True, "runs": [], "stdout": "", "stderr": ""}
                    else:
                        result = run_parameter_sweep_with_matlab(
                            path,
                            block_path=block_path,
                            parameter=parameter,
                            values=parsed,
                            stop_time=stop_time,
                            matlab=self.matlab,
                            timeout=self.timeout,
                            on_process=set_process,
                            cancelled=lambda: bool(job.get("cancel_requested")),
                        )
                with self._lock:
                    job["result"] = result
                    job["state"] = "cancelled" if result.get("cancelled") else "finished"
            except Exception as exc:  # noqa: BLE001 - worker failures are reported through job status
                with self._lock:
                    job["error"] = str(exc)
                    job["state"] = "cancelled" if job.get("cancel_requested") else "failed"
            finally:
                with self._lock:
                    job["process"] = None
                    job["finished_at"] = time.time()
                    if self._active == job_id:
                        self._active = None

        threading.Thread(target=worker, name=f"slxstudio-sweep-{job_id[:8]}", daemon=True).start()
        return self.status(job_id)

    def status(self, job_id: str) -> dict[str, Any]:
        with self._lock:
            self._prune_jobs_locked()
            job = self._jobs.get(str(job_id))
            if not job:
                raise ValueError("unknown parameter sweep job")
            payload = {k: job[k] for k in ("id", "path", "state", "started_at")}
            if job.get("finished_at"):
                payload["finished_at"] = job["finished_at"]
            if job.get("result") is not None:
                payload["result"] = job["result"]
            if job.get("error"):
                payload["error"] = job["error"]
            return payload

    def stop(self, job_id: str) -> dict[str, Any]:
        with self._lock:
            job = self._jobs.get(str(job_id))
            if not job:
                raise ValueError("unknown parameter sweep job")
            if job.get("state") != "running":
                return self.status(job_id)
            job["cancel_requested"] = True
            proc = job.get("process")
            if isinstance(proc, subprocess.Popen) and proc.poll() is None:
                try:
                    proc.terminate()
                    proc.wait(timeout=2.0)
                except subprocess.TimeoutExpired:
                    proc.kill()
                except OSError:
                    pass
            return self.status(job_id)

    def stop_all(self) -> None:
        with self._lock:
            ids = [job_id for job_id, job in self._jobs.items() if job.get("state") == "running"]
        for job_id in ids:
            try:
                self.stop(job_id)
            except (ValueError, OSError):
                pass
